CREATE TABLE IF NOT EXISTS receipt_requests (
 sequence_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 chain_request_id VARCHAR(66) NOT NULL UNIQUE,
 chain_id BIGINT UNSIGNED NOT NULL,
 contract_address VARCHAR(42) NOT NULL,
 tracking_id VARCHAR(66) NOT NULL,
 tenant_id VARCHAR(66) NOT NULL,
 entity_id VARCHAR(66) NOT NULL,
 source_organization_id VARCHAR(66) NOT NULL,
 requester_organization_id VARCHAR(66) NOT NULL,
 requester_account_id CHAR(36) NOT NULL,
 requester_wallet VARCHAR(42) NOT NULL,
 source_route_id VARCHAR(66) NOT NULL,
 received_route_id VARCHAR(66) NOT NULL,
 quantity BIGINT UNSIGNED NOT NULL,
 requested_version BIGINT UNSIGNED NOT NULL,
 request_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 request_hash VARCHAR(66) NOT NULL,
 request_json JSON NOT NULL,
 status ENUM('WAITING_APPROVAL','APPROVING','CONFIRMED','DECLINED','CANCELLED','EXPIRED','FAILED') NOT NULL DEFAULT 'WAITING_APPROVAL',
 approver_account_id CHAR(36) NULL,
 approval_key CHAR(64) NULL,
 prepared_json JSON NULL,
 result_json JSON NULL,
 transaction_hash VARCHAR(66) NULL,
 error_code VARCHAR(64) NULL,
 attempts INT UNSIGNED NOT NULL DEFAULT 0,
 next_attempt_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 lease_token CHAR(36) NULL,
 lease_until DATETIME(3) NULL,
 expires_at DATETIME(3) NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY receipt_retry(chain_id,contract_address,requester_organization_id,request_key),
 KEY receipt_incoming(chain_id,contract_address,source_organization_id,sequence_id),
 KEY receipt_outgoing(chain_id,contract_address,requester_organization_id,sequence_id),
 KEY receipt_dispatch(status,next_attempt_at,lease_until),
 KEY receipt_source(chain_id,contract_address,tenant_id,entity_id,source_route_id,status),
 CONSTRAINT receipt_positive_quantity CHECK(quantity>0 AND quantity<=9007199254740991)
);

ALTER TABLE erp_operations MODIFY status ENUM('QUEUED','PROCESSING','RETRY','WAITING_APPROVAL','CONFIRMED','FAILED','CANCELLED') NOT NULL DEFAULT 'QUEUED';
