export const traceForgeReadAbi = [
  {
    type:
      "function",
    name:
      "getTenant",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "tuple",
        components: [
          {
            name:
              "exists",
            type:
              "bool",
          },
          {
            name:
              "active",
            type:
              "bool",
          },
          {
            name:
              "metadataHash",
            type:
              "bytes32",
          },
          {
            name:
              "createdAt",
            type:
              "uint64",
          },
        ],
      },
    ],
  },

  {
    type:
      "function",
    name:
      "getOrganization",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "organizationId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "tuple",
        components: [
          {
            name:
              "exists",
            type:
              "bool",
          },
          {
            name:
              "active",
            type:
              "bool",
          },
          {
            name:
              "metadataHash",
            type:
              "bytes32",
          },
          {
            name:
              "createdAt",
            type:
              "uint64",
          },
        ],
      },
    ],
  },

  {
    type:
      "function",
    name:
      "getWalletBinding",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "wallet",
        type:
          "address",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "tuple",
        components: [
          {
            name:
              "organizationId",
            type:
              "bytes32",
          },
          {
            name:
              "active",
            type:
              "bool",
          },
        ],
      },
    ],
  },

  {
    type:
      "function",
    name:
      "isActiveWalletForOrganization",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "wallet",
        type:
          "address",
      },
      {
        name:
          "organizationId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "bool",
      },
    ],
  },

  {
    type:
      "function",
    name:
      "getTenantMembership",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "organizationId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "tuple",
        components: [
          {
            name:
              "exists",
            type:
              "bool",
          },
          {
            name:
              "active",
            type:
              "bool",
          },
          {
            name:
              "joinedAt",
            type:
              "uint64",
          },
        ],
      },
    ],
  },

  {
    type:
      "function",
    name:
      "isActiveTenantMember",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "organizationId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "bool",
      },
    ],
  },

  {
    type:
      "function",
    name:
      "hasCapability",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "wallet",
        type:
          "address",
      },
      {
        name:
          "roleId",
        type:
          "bytes32",
      },
      {
        name:
          "capability",
        type:
          "uint8",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "bool",
      },
    ],
  },

  {
    type:
      "function",
    name:
      "getEntity",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "entityId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "tuple",
        components: [
          {
            name:
              "entityType",
            type:
              "bytes32",
          },
          {
            name:
              "metadataHash",
            type:
              "bytes32",
          },
          {
            name:
              "currentState",
            type:
              "bytes32",
          },
          {
            name:
              "currentCustodian",
            type:
              "bytes32",
          },
          {
            name:
              "createdAt",
            type:
              "uint64",
          },
          {
            name:
              "updatedAt",
            type:
              "uint64",
          },
          {
            name:
              "exists",
            type:
              "bool",
          },
          {
            name:
              "closed",
            type:
              "bool",
          },
        ],
      },
    ],
  },

  {
    type:
      "function",
    name:
      "hasPendingCustodyTransfer",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "entityId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "bool",
      },
    ],
  },

  {
    type:
      "function",
    name:
      "getPendingCustodyTransfer",
    stateMutability:
      "view",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "entityId",
        type:
          "bytes32",
      },
    ],
    outputs: [
      {
        name:
          "",
        type:
          "tuple",
        components: [
          {
            name:
              "fromOrganizationId",
            type:
              "bytes32",
          },
          {
            name:
              "toOrganizationId",
            type:
              "bytes32",
          },
          {
            name:
              "proposedBy",
            type:
              "address",
          },
          {
            name:
              "proposedAt",
            type:
              "uint64",
          },
          {
            name:
              "exists",
            type:
              "bool",
          },
        ],
      },
    ],
  },
] as const;
