export const traceForgeWriteAbi = [
  {
    type:
      "event",
    name:
      "CustodyTransferred",
    anonymous:
      false,
    inputs: [
      {
        indexed:
          true,
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        indexed:
          true,
        name:
          "entityId",
        type:
          "bytes32",
      },
      {
        indexed:
          true,
        name:
          "fromOrganizationId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "toOrganizationId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "roleId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "actor",
        type:
          "address",
      },
      {
        indexed:
          false,
        name:
          "eventType",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "evidenceHash",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "acceptedAt",
        type:
          "uint64",
      },
    ],
  },

  {
    type:
      "function",
    name:
      "acceptCustodyTransfer",
    stateMutability:
      "nonpayable",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "roleId",
        type:
          "bytes32",
      },
      {
        name:
          "entityId",
        type:
          "bytes32",
      },
      {
        name:
          "eventType",
        type:
          "bytes32",
      },
      {
        name:
          "evidenceHash",
        type:
          "bytes32",
      },
    ],
    outputs: [],
  },

  {
    type:
      "function",
    name:
      "proposeCustodyTransfer",
    stateMutability:
      "nonpayable",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "roleId",
        type:
          "bytes32",
      },
      {
        name:
          "entityId",
        type:
          "bytes32",
      },
      {
        name:
          "toOrganizationId",
        type:
          "bytes32",
      },
      {
        name:
          "eventType",
        type:
          "bytes32",
      },
      {
        name:
          "evidenceHash",
        type:
          "bytes32",
      },
    ],
    outputs: [],
  },

  {
    type:
      "event",
    name:
      "CustodyTransferProposed",
    anonymous:
      false,
    inputs: [
      {
        indexed:
          true,
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        indexed:
          true,
        name:
          "entityId",
        type:
          "bytes32",
      },
      {
        indexed:
          true,
        name:
          "fromOrganizationId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "toOrganizationId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "roleId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "actor",
        type:
          "address",
      },
      {
        indexed:
          false,
        name:
          "eventType",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "evidenceHash",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "proposedAt",
        type:
          "uint64",
      },
    ],
  },

  {
    type:
      "event",
    name:
      "TraceRecorded",
    anonymous:
      false,
    inputs: [
      {
        indexed:
          true,
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        indexed:
          true,
        name:
          "entityId",
        type:
          "bytes32",
      },
      {
        indexed:
          true,
        name:
          "eventType",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "organizationId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "roleId",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "actor",
        type:
          "address",
      },
      {
        indexed:
          false,
        name:
          "evidenceHash",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "stateAfter",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "metadataHashAfter",
        type:
          "bytes32",
      },
      {
        indexed:
          false,
        name:
          "timestamp",
        type:
          "uint64",
      },
    ],
  },
] as const;
