export const traceForgeWriteAbi = [
  {
    type:
      "function",
    name:
      "proposeCustodyTransfer",
    stateMutability:
      "nonpayable",
    inputs: [
      {
        name:
          "tenantId",
        type:
          "bytes32",
      },
      {
        name:
          "roleId",
        type:
          "bytes32",
      },
      {
        name:
          "entityId",
        type:
          "bytes32",
      },
      {
        name:
          "toOrganizationId",
        type:
          "bytes32",
      },
      {
        name:
          "eventType",
        type:
          "bytes32",
      },
      {
        name:
          "evidenceHash",
        type:
          "bytes32",
      },
    ],
    outputs: [],
  },
] as const;
